home/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView, name="home"),
    
]

library/urls.py
from django.urls import path

from.views import UploadFileView

urlpatterns = [
    path("", UploadFileView, name="upload_book",)
]

schedules/urls.py
from django.urls import path

from .views import randomPasswordView, schedulesPageView, currentTimeView

urlpatterns = [
    path("", schedulesPageView, name="schedules"),
    path("schedules.random_password/", randomPasswordView, name="random_password"),
    path("schedules.time_now/", currentTimeView, name="time_now"),
]

study/urls.py
from django.urls import path

from .views import StudyView, subjectView, PomodoroTimerView
from.views import FlashcardCreateView, TopicCreateView, SubjectCreateView, TopicDetailView

urlpatterns = [
    path("", StudyView, name="study"),
    path("pomodoro_timer/", PomodoroTimerView.as_view(), name="pomodoro_timer"),
    path("subjects/", subjectView, name="subjects"),
    path("subjects/flashcard_add/", FlashcardCreateView.as_view(), name="flashcard_add"),
    path("topic_add/", TopicCreateView.as_view(), name="topic_add"),
    path("subject_add/", SubjectCreateView.as_view(), name="subject_add"),
    path("subjects/topic_detail/<int:pk>/", TopicDetailView.as_view(), name="topic_detail"),
]

home/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
""" AbstractUser is used to create custom models """


# Create your models here.

library/models.py
from django.db import models

# Create your models here.
class NewBook(models.Model):
    bookTitle = models.CharField(max_length=50)
    book = models.FileField(null=True) # FileField is used for file input

schedules/models.py
from django.db import models

# Create your models here.

class PasswordOperator(models.Model):
    password = models.CharField(max_length=10, null=False)
    time = models.DateTimeField(null=False)
    label = models.CharField(max_length=20, null=False)

    def __str__(self):
        return self.label

class Schedule(models.Model):
    schedule = models.CharField(null=False, max_length=100)
    time = models.DateTimeField(null=False)

    def __str__(self):
        return self.schedule 

study/models.py
from django.db import models

from django.urls import reverse

# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False,)
    
    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=50, null=False)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.name

class Flashcard(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=False)
    question = models.CharField(max_length=500, null=False)
    answer = models.TextField(null=False)

    # Displays the question of a particular model to the user
    def __str__(self):
        return self.question
    

library/forms.py
from django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()
    """widget=forms.ClearableFileInput(attrs={"multiple": True}) can be used to allow uploading
    of multiple files"""

schedules/forms.py
from django import forms
from .models import PasswordOperator, Schedule


class PasswordForm(forms.ModelForm):
    class Meta:
        model = PasswordOperator
        fields = ["password", "time", "label"]
        widgets = {
            # Provides a password input widget for the specified fields
            "password":forms.PasswordInput(attrs={"class": "form-control", "type": "password", "placeholder": "password"}),
            "time": forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime-local"}),
            "label": forms.TextInput(attrs={"class": "form-control", "placeholder": "Lock Label. e.g. 'Anime'... "})   
        }

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ["schedule", "time"]
        widgets = {
           "time": forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime-local"}),
           "schedule":forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter New Task"})
        }

study/forms.py
from django import forms

from .models import Subject

class NewSubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ["name"]

class NewTopicForm(forms.ModelForm):
    class Meta:
        model = Subject
        subject = forms.ModelChoiceField(queryset=Subject.objects.all())
        fields = ["name",]

home/views.py
from django.shortcuts import render

# Create your views here.
def HomePageView(request):
    return render(request, "home.html",)

library/views.py
from django.shortcuts import render, HttpResponse

from .forms import UploadFileForm

from .models import NewBook

# Create your views here.
def UploadFileView(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        file = request.FILES["file"] # "File" is the file in UploadFIleForm
        title = request.POST["title"] # Apart from files all other items are obtained using POST

        # Creates a new object in NewBook Model
        newBook = NewBook.objects.create(book = file, bookTitle = title)
        newBook.save()

        return HttpResponse(f"The file {newBook.book} is titled {newBook.bookTitle}")

    else:
        form = UploadFileForm
    return render(request, "library.html", {"form": form})

schedules/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .models import PasswordOperator, Schedule
from .forms import PasswordForm, ScheduleForm
from .password import generatePassword

from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy, reverse

from plyer import notification
from datetime import datetime

# Create your views here.
class PasswordView(CreateView):
    model = PasswordOperator
    form_class = PasswordForm
    success_url = "schedules"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Edits the context 'form' to be used in html 
        context["passwordForm"] = context["form"]
        return context 


class ScheduleCreateView(CreateView):
    model = Schedule
    form_class = ScheduleForm
    success_url = reverse_lazy("schedules")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Edits the context 'form' to be used in html 
        context["scheduleForm"] = context["form"]
        return context
    

def schedulesPageView(request):
    if request.method == 'POST':
        # Checks if the request is a "passLock" request or "schedule" request
        if "password" in request.POST:
            # Assigns data from the request into a variable
            password_data = request.POST
            # Creates and saves a new PasswordOperator object using the data from the request
            new_password_obj = PasswordOperator(
                password = password_data["password"], 
                time = password_data["time"],
                label = password_data["label"],
                )
            new_password_obj.save()
        else:
            schedule_data = request.POST
            new_schedule_obj = Schedule(schedule = schedule_data["schedule"], time = schedule_data["time"])
            new_schedule_obj.save()
        
        # redirects url to "schedules" url (refreshes the page)
        return redirect(reverse("schedules"))
    
    else:
        schedule_response = ScheduleCreateView.as_view()(request)
        password_response = PasswordView.as_view()(request)
        
        context = {}
        context.update(schedule_response.context_data)
        context.update(password_response.context_data)
        context["schedule_objects"] = Schedule.objects.all()
        context["pass_seal_objects"] = PasswordOperator.objects.all()
        return render(request, "schedules.html", context)


# Packs random password in a json response
def randomPasswordView(request):
    random_password = generatePassword()
    pasword_dict = {"random_password": random_password}

    return JsonResponse(pasword_dict)

def currentTimeView(request):
    now = datetime.now()

    # Date
    year_now = now.year
    month_now = now.month
    month_now_str = now.strftime("%B")
    day_now = now.day
    day_now_str = now.strftime("%A")

    # Time
    hour_now = now.hour
    minute_now = now.minute
    second_now = now.second

    time_dict = {
        "now": now,

        # Date 
        "year_now": year_now,
        "month_now": month_now,
        "month_now_str": month_now_str,
        "day_now": day_now,
        "day_now_str": day_now_str,

        # Time
        "hour_now": hour_now,
        "minute_now": minute_now,
        "second_now": second_now,
    }

    return JsonResponse(time_dict)

study/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, DetailView, TemplateView

from django.views.generic.edit import CreateView

from .models import Subject, Topic, Flashcard

from .forms import NewSubjectForm, NewTopicForm

from django.urls import reverse_lazy

# Create your views here.
def StudyView(request):
    return render(request, "study.html")

# Pomodoro Technique View
class PomodoroTimerView(TemplateView):
    template_name = "pomodoro_timer.html"

# Flashcards Technique View
def subjectView(request):
    subjects = SubjectListView.as_view()(request)
    topics  = TopicListView.as_view()(request)

    context = {}
    context.update(subjects.context_data)
    context.update(topics.context_data)

    return render(request, "subjects.html", context=context)

class SubjectCreateView(CreateView):
    model = Subject
    fields = ["name"]
    success_url = reverse_lazy("topic_add")
    template_name = "subject_add.html"

class SubjectListView(ListView):
    model = Subject

class TopicCreateView(CreateView):
    model = Topic
    fields = ["subject", "name"]
    template_name = "topic_add.html"
    success_url = reverse_lazy("flashcard_add")

class TopicListView(ListView):
    model = Topic
    fields = ["name"]

class TopicDetailView(DetailView):
    template_name = "topic_detail.html"
    model = Topic

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["flashcards"] = Flashcard.objects.all()
        return context

class FlashcardCreateView(CreateView):
    model = Flashcard
    fields = ["topic", "question", "answer"]
    template_name = "flashcard_add.html"
    success_url = reverse_lazy("subjects")

class FlashcardListView(ListView):
    model = Flashcard
    fields = ["question", "answer"]



















# Future References
def SubjectView(request):
    newSubject = SubjectCreateView.as_view()(request)
    newTopic = TopicCreateView.as_view()(request)
    subjects = SubjectListView.as_view()(request)
    topics = TopicListView.as_view()(request)

    context = {}
    context.update(newSubject.context_data)
    context.update(subjects.context_data)
    context.update(topics.context_data)
    #context.update(newTopic.context_data)

    return render(request, "subjects.html", context=context)


def SubjectView(request):
    if request.method == "POST":
        print(request.POST)
        subjForm = NewSubjectForm(request.POST)
        topicForm = Topic.objects.create(request.POST)
        if subjForm.is_valid():
            subjForm.save()
            print("Subject saved!")
            return redirect("subjects")
        
        elif topicForm.is_valid():
            topicForm.save()
            print("topic saved!")
            return redirect("subjects")
        else:
            print("No valid forms available!")
    
    context = {
        "subjects": Subject.objects.all(), # SubjectListView
        "topics": Topic.objects.all(), # TopicListView
        "NewSubject": NewSubjectForm,
        "NewTopic": Subject,
    }
    return render(request, "subjects.html", context=context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-icons/font/bootstrap-icons.css">
    <title>Harmony</title>
</head>
<body>
    <div id="overlay" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeCurtain()">&times;</a>
        <div id="overlay-content" class="overlay-content"></div>
    </div>
    <header>
        <div id="home-nav-panel">
            <div class="menu-icon" onclick="crossMenu()">
                <div class="bar" id="bar1"></div>
                <div class="bar" id="bar2"></div>
                <div class="bar" id="bar3"></div>
            </div>
            <div id="nav-left">
                <a class="home-nav-contents" href="{% url 'home' %}">Home</a>
                <a class="home-nav-contents" href="#">Search</a>
            </div>
            <div id="nav-right">
                <div id="avatar">
                    <a href="">
                        <img alt="avatar" src="{% static 'images/avatar.png' %}">
                    </a>
                </div>
            </div>
        </div>
        <div style="width: 100%; height: 5px; position: fixed; top: 50px; left: 0; 
        background-color: lavender; z-index: 1;"></div>
    </header>
    <div class="side-nav-panel">
        <div id="inner-side-nav-panel">
            <div id="opening-message-slot">
                <h1>New Chapter</h1>
                <p id="opening-message"></p>
            </div>
            <a href="{% url 'home' %}" id="home">Home</a>
            <a href="#" id="habit-tracker">Habit Tracker</a>
            <a href="{% url 'schedules' %}" id="schedules">Schedules</a>
            <a href="{% url 'upload_book' %}" id="library">Library</a>
            <a href="{% url 'study' %}" id="study">Study</a><br><br>
            <a href="#" id="journal">My Personal Journal</a>
        </div>
    </div>
    <main>
        {% block mainbody %}
        {% endblock mainbody %}
    </main>
    </body>
<script src="{% static 'javascript/script.js' %}"></script>
</html>

templates/flashcard_add.html
{% extends "base.html" %}
{% load static %}

{% block mainbody %}
<div class="form-page-main">
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="save-btn" value="Save">
    </form>
    <p>Can't find a topic? <a href="{% url 'topic_add' %}">Add</a> a new one.</p>
</div>
{% endblock mainbody %}

templates/home.html
{% extends "base.html" %}

{% load static %}

{% block mainbody %}
<br><br>
<div class="headline">
    <!-- Slideshow -->
    <div class="slide fade">
        <img class="slide-img" src="{% static 'images/girl-with-blue-bubble.png' %}" alt="image">
        <div id="value">1 / 5</div>
        <div id="caption">Caption 1</div>
        
        <!-- Left and Right buttons -->
        <a id="prev" onclick="">&#10094;</a>
        <a id="next" onclick="nextSlide(1)">&#10095;</a>
    </div>
</div><br><br>
<div class="feed">
    <h2>"The Power of Action: Breaking Free from Laziness and Pursuing Your Dreams"</h2>
    <p>
        "Nobody is born lazy. Laziness is a habit that we develop over time, and it's a habit that we can break. 
        The first step to overcoming laziness is to acknowledge that you have a problem. You have to be honest with 
        yourself and admit that you're not putting in the effort that you need to in order to reach your goals.

        The next step is to create a plan. You need to set clear and specific goals for yourself, and you need to 
        break them down into smaller, more manageable tasks. This will make it easier for you to get started, and it 
        will give you a sense of accomplishment as you check off each task.

        It's also important to surround yourself with positive influences. Find people who are motivated and driven, 
        and spend time with them. Their enthusiasm and energy will rub off on you, and it will help to keep you focused 
        and on track.

        Finally, remember that progress, not perfection, is what matters. It's okay to make mistakes and have setbacks 
        along the way. The important thing is to keep moving forward and to never give up on yourself or your dreams. 
        With determination, hard work, and a positive attitude, you can overcome laziness and achieve anything you set 
        your mind to."
    </p>
</div><br>

<div class="feed">
    <h2>"Navigating Change: Embracing New Opportunities and Overcoming Obstacles"</h2>
    <p>
        Overcoming addiction is not an easy journey, but it is a journey worth taking. It takes courage and strength to 
        admit that you have a problem, and it takes even more courage and strength to take the necessary steps to overcome it. 
        But know that you are not alone in this journey. There are many people who have gone through the same struggles as you 
        and have come out on the other side stronger than ever before.

        Remember that you are not defined by your addiction. Your addiction does not define who you are as a person. 
        You are so much more than your addiction. You have the power within you to break free from its grip and to create a new 
        and fulfilling life for yourself.

        Take it one day at a time, and don't be too hard on yourself. Recovery is not a linear process, and there will be ups and 
        downs along the way. But with each step forward, you are becoming stronger and more resilient. Celebrate your successes, 
        no matter how small they may seem, and use them as fuel to keep going.

        Surround yourself with people who support your recovery journey and who uplift you. Seek out professional help if needed, 
        and don't be afraid to ask for help when you need it. Remember that it's okay to not be okay, and that there is always hope 
        for a brighter future.

        You are worthy of a happy and fulfilling life, free from the chains of addiction. Keep pushing forward, keep fighting, and never give up on yourself. You've got this.
    </p>
</div><br>

<div class="feed">
    <h2>"From Chaos to Clarity: The Power of Organizing Your Life"</h2>
    <p>
        Organizing your life can be a daunting task, but it is also one of the most rewarding things you can do for yourself. 
        The benefits of living an organized life are numerous and far-reaching. When you take the time to organize your life, 
        you will find that you have more time and energy for the things that matter most to you. You will also experience a 
        greater sense of control and order in your life, which can lead to increased happiness, reduced stress, and improved 
        mental health.
    </p>
</div>
<script>
    function nextSlide(y) {
        let x = images.length;
        let nextSlide = ((currentSlide + 1) % x);
        console.log(nextSlide)
        slide = document.querySelector(".slide-img");
        slide.setAttribute("src", images[nextSlide]);
        currentSlide = nextSlide;
    }

    let currentSlide = 0;
    var image0 = "{% static 'images/girl-with-blue-bubble.png' %}";
    var image1 = "{% static 'images/fix-yourself.jpg' %}";
    var image2 = "{% static 'images/journal.png' %}";
    var image3 = "{% static 'images/meet-friends.jpg' %}";
    var image4 = "{% static 'images/time-management.jpg' %}";
    var image5 = "{% static 'images/time-management2.jpg' %}";

    let images = [image0, image1, image2, image3, image4, image5];

    document.querySelector("#home").classList.add("active");
    setInterval(nextSlide, 5000);
</script>
{% endblock mainbody %}

templates/index.html
{% extends "base.html" %}

{% block mainbody %}
{{form.as_p}}
<input type="submit" value="save">
{% endblock mainbody %}

templates/library.html
{% extends "base.html" %}
{% load static %}

{% block mainbody %}
<div style="margin: auto; padding-top: 20px; width: 500px;">
    <form action="{% url 'upload_book' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>File: {{ form.file }}</p>
        <p>Title: {{ form.title }}</p>
        <input type="submit" value="Upload File">
</div>
<script>
    document.querySelector("#library").classList.add("active");
</script>
{% endblock mainbody %}

templates/pomodoro_timer.html
{% extends "base.html" %}

{% load static %}

{% block mainbody %}
<div id="time-plate" style="width: fit-content; margin: 15% auto;">
    <h1 class="timer" style="font-size: 4rem;">00:00:00</h1>
    <button onclick="startCountdown()">Start</button>
    <button>Stop</button>
</div>
<script>
    function startCountdown() {
        var secs = 00;
        var mins = 25;
        var hrs = 00;

        countdown = setInterval(() => {
            if (secs == 00) {
                mins--;
                secs = 60;
            }
            secs--

            updatedTime = `${hrs.toString().padStart(2, "0")}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`
            document.querySelector(".timer").innerHTML = updatedTime;

            if (mins == 00) {
                clearInterval(countdown);
            }

        }, 1000);
    }


    document.querySelector("#study").classList.add("active");
</script>
{% endblock mainbody %}

templates/schedules.html
{% extends "base.html" %}
{% load static %}

{% block mainbody %}
<link rel="stylesheet" href="{% static 'css/schedules.css' %}">
<!-- Pass seal form -->
<div id="pass-seal" class="mini-form">
    <div id="body">
        <div id="head">
            <h1 id="title">Pass Seal</h1>
        </div>
        <div>
            <form method="POST">{% csrf_token %}
                <p>Generate random password to keep distractions safely sealed away</p>
                <p>{{ passwordForm.label }}</p>
                <p>{{ passwordForm.password }}</p>
                <button id="pass-gen" class="btn" onclick="fetchPassword()">Generate</button>
                <button id="pass-copy" class="btn" onclick="copyPassword()">Copy</button>
                <h3>Recovery Period</h3>
                <p>{{ passwordForm.time }}</p>
                <input class="btn" type="submit" value="Save">
            </form>
        </div>
    </div>
</div>  
<!-- Schedule Form -->
<div id="schedule" class="mini-form">
    <div id="body">
        <div id="head">
            <h1 id="title">Schedule</h1>
        </div>
        <div>
            <form method="POST">{% csrf_token %}
                <p>Keep track of your tasks and give your brain a break!!</p>
                <p>{{ scheduleForm.schedule }}</p>
                <h3>Due Period</h3>
                <p>{{ scheduleForm.time }}</p>
                <input class="btn" type="submit" value="Save">
            </form>
        </div>
    </div>
</div>

<!-- Main schedules template -->
<div class="main-page">
    <div id="schedules-main-page-header" class="main-page-header">
        <h2>&#128197;  My Schedule</h2>
        <span class="main-page-sub-header">
            <button id="schedule-menu-btn" onclick="toggle_show_item('schedule-menu')">tasks&#9656;</button>
            <div id="schedule-menu" class="dropdown-menu">
                <a id="tasks">All</a>
                <a id="pass-lock">Today</a>
                <a style="border-bottom: 1px solid #f1f1f1;">This Week</a>
                <a>
                    <input type="checkbox" id="pass-seal-op" name="pass-seal-op">
                    <label for="pass-seal-op">Pass Seals</label>
                </a>
            </div>
            <div class="time-plate">
                <button id="current-time"></button>
            </div>
        </span>
    </div>
    <div id="schedules-main-page-body" class="main-page-body"> 
        <div>
            <div class="schedule-tag">
                <h5>&#11088;   Todo</h5>
            </div>
            <div class="schedule-tag">
                <h5>&#8987;   Due</h5>
            </div>
            <div class="schedule-tag">
                <h5>&#9989;   Completed</h5>
            </div>
        </div>
        {% if schedule_objects %}
            {% for task in schedule_objects %}
                <div id="task-item" class="task-item">
                    <p style="font-size: 11px; padding: 0 10px;">{{ task.time }}</p>
                    <h3 style="padding: 10px;">{{ task.schedule }}</h3>
                </div>
            {% endfor %}
        {% else %}
            <h3>No Tasks Today. <a onclick="openCurtain('schedule')">Add</a>a new task.</h3>
        {% endif %}
    </div>
    <button onclick="toggle_show_item('schedule-btn')">&#10133;&#9662;</button>
    <div id="schedule-btn" style="display: none;">
        <button class="btn" onclick="openCurtain('pass-seal')">New Time Seal</button>
        <button class="btn" onclick="openCurtain('schedule')">New Task</button>
    </div>

    <!-- Pass Seal -->
    <div id="padlocks" style="display: none; transition: 0.3s;">
        <h2 style="margin-top: 50px;">Pass Seal</h2>
        {% if pass_seal_objects %}
            {% for pas_seal_object in pass_seal_objects %}
                <div class="padlock">
                    <div class="padlock-shackle">
                        <div class="outer"></div>
                        <div class="inner"></div>
                    </div>
                    <div class="padlock-body">
                        <div class="padlock-field" id="padlock-label-field">
                            <p style="padding: 10px; text-align: center;">{{ pas_seal_object.label }}</p>
                        </div>
                        <div class="padlock-field" id="padlock-password-field">
                            <p style="padding: 10px; text-align: center;">{{ pas_seal_object.password }}</p>
                        </div>
                        <div class="padlock-key" onclick="switchText(this, newText='Copy')">Open</div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>No pass seal present today. <a onclick="openCurtain('pass-seal')">click here</a> to add a pass seal.</h3>
        {% endif %}
    </div>
</div>
<script src="{% static 'javascript/schedules.js' %}"></script>
{% endblock mainbody %}

templates/study.html
{% extends "base.html" %}

{% load static %}

{% block mainbody %}
<div class="middle-body">
    <h1>Legends Live Here</h1>
</div>
<div class="right-body">
    <h3 style="text-align: center;">Explore Different Study Techiques</h3>
    <div id="pomorodo-technique" class="study-technique">
        <a href="{% url 'pomodoro_timer' %}">
            <img alt="Pomodoro" src="{% static 'images/pomorodo.gif' %}">
            <p>Pomodoro Technique</p>
        </a>
    </div>
    <div id="flashcards" class="study-technique">
        <a href="{% url 'subjects' %}">
            <img alt="Flashcards" src="{% static 'images/flashcards.gif' %}">
            <p>flashcards Technique</p>
        </a>
    </div>
</div>
<script>
    document.querySelector("#study").classList.add("active");
</script>
{% endblock mainbody %}

templates/subject_add.html
{% extends "base.html" %}
{% load static %}

{% block mainbody %}
<div class="form-page-main">
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="save-btn" value="Save">
    </form>
{% endblock mainbody %}

templates/subjects.html
{% extends "base.html" %}

{% load static %}

{% block mainbody %}
<div class="main-page">
    {% if subject_list %}
        {% for subject in subject_list %}
            <div class="subjects">
                <div class="subject-box">
                    <div href="" class="subject-main" onclick="showTopicMenu(this)">
                        <i class="bi bi-bookmarks" style="color: cadetblue; padding: 2px; transition: 0.3s;"></i>
                        <p class="subject-title" style="font-weight: 700;">{{ subject.name }}</p>
                        <div class="topic-menu">
                            {% for topic in topic_list %}
                                {% if topic.subject == subject %}
                                    <a href="{% url 'topic_detail' topic.pk %}">{{ topic.name }}</a>
                                {% endif %}
                            {% endfor %}
                            <a href="">Add New Topic</a>
                            <a href="">Delete Subject</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <br style="clear: both;">
        <a href="{% url 'flashcard_add' %}" class="add-link">New Flashcard</a>
    {% else %}
        <div>
            <p style="padding: 10px; text-align: center; font-size: 20px;">
                No Flashcards Yet. <a class="add-link" href="{% url 'flashcard_add' %}">Click Here</a> 
                to add a new Flashcard.
            </p>
        </div>
    {% endif %}
<script>
    function showTopicMenu(x) {
        menu = x.children[2];
        icon = x.children[0];

        menu.classList.toggle("show");
        icon.classList.toggle("active-subject");
    }

    document.querySelector("#study").classList.add("active");
</script> 
{% endblock mainbody %}

templates/topic_add.html
{% extends "base.html" %}
{% load static %}

{% block mainbody %}
<div class="form-page-main">
    <form method="POST">{% csrf_token %}
        <p>{{ form.as_p }}</p>
        <input type="submit" class="save-btn" value="Save">
    </form>
    <p>Can't find a Subject? <a href="{% url 'subject_add' %}">Add</a> a new one.</p>
</div>
{% endblock mainbody %}

templates/topic_detail.html
{% extends 'base.html' %}
{% load static %}

{% block mainbody %}
<div class="main-page">
    <p style="font-size: small; font-weight: 700; padding: 10px; font-style: italic;">{{ topic.name }}</p>
    {% for flashcard in flashcards %}
        {% if flashcard.topic.name == topic.name %}
            <div class="flashcard-container">
                <div class="flashcard">
                    <div class="flashcard-front">
                        <h3 style="padding: 10px; white-space: pre-wrap; text-align: center;">{{ flashcard.question }}</h3>
                    </div>
                    <div class="flashcard-back">
                        <h1 style="text-align: center;">Answer</h1>
                        <p style="padding: 10px; white-space: pre-wrap;">{{ flashcard.answer }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
<script>
    document.querySelector("#study").classList.add("active");
</script>
{% endblock mainbody %}